name: 'actions-build-branch-info'
description: 'Return the active build branch names'
inputs:
  exclude-master:
    description: 'Set true to exclude returning the master branch ex: for jobs like ios-democ-test'
    default: false
  latest-rel:
    description: 'Set true to return the latest release branch ex: for jobs like l10n-download'
    default: false
  default-branch:
    description: 'Default branch name of the caller repo'
    default: master
outputs:
  branches-json:
    description: "branch names in a JSON list or a single string for latest-rel"
    value: ${{ steps.branches.outputs.value }}

runs:
  using: "composite"
  steps:
    - name: Branches
      id: branches
      shell: bash
      run: |
        set -x
        default_branch="${{ inputs.default-branch }}"
        echo "INFO inputs.exclude-master: ${{ inputs.exclude-master }}"
        echo "INFO inputs.latest-rel: ${{ inputs.latest-rel }}"
        echo "INFO inputs.default-branch: ${default_branch}"

        if [[ "${{ inputs.latest-rel }}" == "true" ]]; then
            return_str=\"$(echo ${{ env.BRANCH_NAMES }} | tr ' ' '\n' | grep '^rel-' | sort -V | tail -1)\"
        else
            json_str=""
            for item in ${{ env.BRANCH_NAMES }}; do
                if [[ "${{ inputs.exclude-master }}" == "true" && "$item" == "master" ]]; then
                    :
                elif [[ "$json_str" == "" ]]; then
                    json_str="\"$item\""
                else
                    json_str="$json_str, \"$item\""
                fi
            done
            [[ "$default_branch" != "master" ]] && json_str="${json_str/master/$default_branch}"
            return_str="[$json_str]"
        fi
        echo "value=$return_str" >> $GITHUB_OUTPUT
      env:
        BRANCH_NAMES: "master rel-1.190 rel-1.189"
